FROM matomo:latest

# Update packages and install nano
RUN apt-get update && apt-get install nano -y

# Modify the config.ini.php file
# nano config/config.ini.php
# [General]
# ...
# trusted_hosts[] = "localhost:8081"
