version: '3.9'

services:
  matomo:
    image: matomo
    ports:
      - '8081:80'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - matomo_data:/var/www/html

  db:
    image: mysql:latest
    ports:
      - '5550:3306'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  matomo_data:
  db_data:
