# Set the base image to Node.js LTS
FROM node:lts-alpine

# Update packages and install nano
RUN apk update && apk add nano

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . ./

# Expose custom port in the container
EXPOSE 31087

# Run the app
CMD [ "npm", "run", "dev" ]
