version: '3.9'

services:
  matomo:
    image: matomo
    ports:
      - '80:80'
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - matomo_data:/var/www/html

  mysql:
    image: mysql:latest
    ports:
      - '5550:3306'
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  next:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - matomo

volumes:
  matomo_data:
  mysql_data:
