# Set the base image to Node.js LTS
FROM node:lts

# Update packages and install nano
RUN apt-get update && apt-get install nano -y

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code
COPY . ./

# Build the Next.js app
RUN npm run build

# Expose custom port in the container
EXPOSE $PORT

# Run the app
CMD [ "npm", "run", "dev" ]
